apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  - image: busybox
    name: busybox
    command: ["/bin/bash", "-c"]
    arg: ["sleep 1000"]
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
